name: 'Verify Linked Issue'
description: 'A GitHub action that verifies a pull request contains a reference to an issue.'
branding:
    icon: check-square
    color: green
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          if (context.payload.pull_request.body === null) {
            console.log("No Linked Issue Found!");
            core.setFailed('No linked issue found in the pull request description.');
            return;
          }         
                   
          const clickUpIssues = context.payload.pull_request.body.match(/https:\/\/app\.clickup\.com\/.*?\/(SP-\d+)/gm);
          const redmineIssue = context.payload.pull_request.body.match(/https:\/\/redmine\.regulaforensics\.com\//gm);
          
          if (!clickUpIssues && !redmineIssue) {
            console.log("No Linked Issue Found!");
            core.setFailed('No linked issue found in the pull request description.');
          }
